language: elixir
elixir:
  - 1.0.5
otp_release:
  - 17.5
  - 18.0
services: mysql
sudo: false
script:
  - MIX_ENV=mysql mix test
  - MIX_ENV=pg mix test
notifications:
  recipients:
    - elixmoon@gmail.com
